### ISSUE TITLE
There is a way to clean the DB

### ISSUE THREAD

**Issue by kidburglar** [tomjakubowski/yasuc#4]
Hello, there is a way to clean the db other than recreate another db ?
Maybe it would be nice to limit the size of the DB and make an automatic clean ?

Anyway good job, it run smoothly on my nas after rebuilding it with docker.
Strangely https://hub.docker.com/r/yasuc/nginx/ not work for me.

Cheers.

**Comment by tomjakubowski** [comment]
Sorry for the late response. This is out of scope; I would suggest writing your program which opens the database and cleans it as you see fit.
